name       : warzone2100
version    : 3.2.2
release    : 3
source     :
    - https://sourceforge.net/projects/warzone2100/files/releases/3.2.2/warzone2100-3.2.2.tar.xz/download : af5a8dfe9e9df3505ef2543e4e62afb1f61a4ee4cc903f8ff7785f3c79779d18
license    :
    - BSD-3-Clause
    - CC0-1.0
    - CC-BY-SA-3.0
    - GPL-2.0
    - LGPL-2.1
component  : games.strategy
summary    : Warzone 2100, you command the forces of The Project in a battle to rebuild the world after mankind has almost been destroyed by nuclear missiles.
description: |
    Warzone 2100, you command the forces of The Project in a battle to rebuild the world after mankind has almost been destroyed by nuclear missiles.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(glew)
    - pkgconfig(harfbuzz)
    - pkgconfig(libcrypto)
    - pkgconfig(libpng)
    - pkgconfig(openal)
    - pkgconfig(Qt5Script)
    - pkgconfig(sdl2)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
    - pkgconfig(vorbisfile)
    - pkgconfig(xrandr)
    - physfs-devel
setup      : |
    cp $pkgfiles/warzone2100.appdata.xml icons/
    %configure
build      : |
    %make
install    : |
    %make_install
