name       : warzone2100
version    : 3.4.0
release    : 16
source     :
    - https://github.com/Warzone2100/warzone2100/releases/download/3.4.0/warzone2100_src.tar.xz : fe0128b4fe590d29d6f03fc1bc72016448fdb282dd8d9f9fbb4403fe53e4983c
license    :
    - BSD-3-Clause
    - CC0-1.0
    - CC-BY-SA-3.0
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : games.strategy
summary    : Warzone 2100, you command the forces of The Project in a battle to rebuild the world after mankind has almost been destroyed by nuclear missiles
description: |
    In Warzone 2100, you command the forces of The Project in a battle to rebuild the world after mankind has almost been destroyed by nuclear missiles.

    The game offers campaign, multi-player, and single-player skirmish modes. An extensive tech tree with over 400 different technologies, combined with the unit design system, allows for a wide variety of possible units and tactics.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(libcurl)
    - pkgconfig(libsodium)
    - pkgconfig(miniupnpc)
    - pkgconfig(openal)
    - pkgconfig(physfs)
    - pkgconfig(sdl2)
    - pkgconfig(theora)
    - pkgconfig(vorbisfile)
setup      : |
    %cmake_ninja \
        -DENABLE_DOCS=OFF \
        -DWZ_DISTRIBUTOR="Solus"
build      : |
    %ninja_build
install    : |
    %ninja_install
