name       : warzone2100
version    : 3.2.1
release    : 1
source     :
    - http://netix.dl.sourceforge.net/project/warzone2100/releases/3.2.1/warzone2100-3.2.1.tar.xz : 0f66b76c50c598abcc895134bd49aab5dd46dcf8135645f2505e93077402a6d9
license    :
    - BSD-3-Clause
    - CC0-1.0
    - CC-BY-SA-3.0
    - GPL-2.0
    - LGPL-2.1
component  : games.strategy
summary    : Warzone 2100, you command the forces of The Project in a battle to rebuild the world after mankind has almost been destroyed by nuclear missiles.
description: |
    Warzone 2100, you command the forces of The Project in a battle to rebuild the world after mankind has almost been destroyed by nuclear missiles.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(glew)
    - pkgconfig(libcrypto)
    - pkgconfig(libpng)
    - pkgconfig(openal)
    - pkgconfig(Qt5Core)
    - pkgconfig(sdl2)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
    - pkgconfig(vorbisfile)
    - pkgconfig(xrandr)
    - physfs-devel
setup      : |
    cp $pkgfiles/warzone2100.appdata.xml icons/
    %configure
build      : |
    %make
install    : |
    %make_install
