name       : warzone2100
version    : 3.2.3
release    : 4
source     :
    - https://netcologne.dl.sourceforge.net/project/warzone2100/releases/3.2.3/warzone2100-3.2.3.tar.xz : fcab9e860203e7dacda6ee60384da490a9d44aeafc07aa31ff25f9c548be7582
license    :
    - BSD-3-Clause
    - CC0-1.0
    - CC-BY-SA-3.0
    - GPL-2.0
    - LGPL-2.1
component  : games.strategy
summary    : Warzone 2100, you command the forces of The Project in a battle to rebuild the world after mankind has almost been destroyed by nuclear missiles.
description: |
    In Warzone 2100, you command the forces of The Project in a battle to rebuild the world after mankind has almost been destroyed by nuclear missiles.

    The game offers campaign, multi-player, and single-player skirmish modes. An extensive tech tree with over 400 different technologies, combined with the unit design system, allows for a wide variety of possible units and tactics.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(glew)
    - pkgconfig(harfbuzz)
    - pkgconfig(libcrypto)
    - pkgconfig(libpng)
    - pkgconfig(openal)
    - pkgconfig(Qt5Script)
    - pkgconfig(sdl2)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
    - pkgconfig(vorbisfile)
    - pkgconfig(xrandr)
    - physfs-devel
setup      : |
    cp $pkgfiles/warzone2100.appdata.xml icons/
    %configure --disable-debug --with-distributor="Solus"
build      : |
    %make
install    : |
    %make_install
